### ISSUE TITLE
You're using HttpClient wrong

### ISSUE THREAD

**Issue by mtranchi** [nieltg/CodeHollow.FeedReader.Core#1]
It needs to be static, can't use it in a using statement.
Check out this article [YOU'RE USING HTTPCLIENT WRONG AND IT IS DESTABILIZING YOUR SOFTWARE](https://aspnetmonsters.com/2016/08/2016-08-27-httpclientwrong/)

**Comment by nieltg** [comment]
*for the sake of completeness since I have replied this in another way.*

This issue has been solved on the upstream project, [here](https://github.com/codehollow/FeedReader/blob/4beec09f36084afdb7ccca9f106d770b356b3c8c/FeedReader/Helpers.cs#L22) to be exact.
Please use it since it has supported *.NET Standard* framework.

Thank you very much for your report, @mtranchi.
